### ISSUE TITLE
Could not initialize class org.xerial.snappy.Snappy

### ISSUE THREAD

**Issue by Dreamter** [panovvv/bigdata-docker-compose#2]
Hi, 

When I try to save the spark dataframe content to parquet, spark throws the following error:

%spark
`df.write.parquet("/grades")`

> org.apache.spark.SparkException: Job aborted.
>   at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:198)
>   at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:159)
>   at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:104)
>   at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:102)
>   at org.apache.spark.sql.execution.command.DataWritingCommandExec.doExecute(commands.scala:122)
>   at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
>   at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
>   at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
>   at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
>   at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
>   at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
>   at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:83)
>   at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:81)
>   at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
>   at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
>   at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)
>   at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
>   at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
>   at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
>   at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:285)
>   at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)
>   at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:229)
>   at org.apache.spark.sql.DataFrameWriter.parquet(DataFrameWriter.scala:566)
>   ... 47 elided
> Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 3.0 failed 4 times, most recent failure: Lost task 0.3 in stage 3.0 (TID 9, worker1, executor 1): org.apache.spark.SparkException: Task failed while writing rows.
> 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:257)
> 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:170)
> 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:169)
> 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:123)
> 	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
> 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy
> 	at org.apache.parquet.hadoop.codec.SnappyCompressor.compress(SnappyCompressor.java:67)
> 	at org.apache.hadoop.io.compress.CompressorStream.compress(CompressorStream.java:81)
> 	at org.apache.hadoop.io.compress.CompressorStream.finish(CompressorStream.java:92)
> 	at org.apache.parquet.hadoop.CodecFactory$HeapBytesCompressor.compress(CodecFactory.java:165)
> 	at org.apache.parquet.hadoop.ColumnChunkPageWriteStore$ColumnChunkPageWriter.writePage(ColumnChunkPageWriteStore.java:95)
> 	at org.apache.parquet.column.impl.ColumnWriterV1.writePage(ColumnWriterV1.java:147)
> 	at org.apache.parquet.column.impl.ColumnWriterV1.flush(ColumnWriterV1.java:235)
> 	at org.apache.parquet.column.impl.ColumnWriteStoreV1.flush(ColumnWriteStoreV1.java:122)
> 	at org.apache.parquet.hadoop.InternalParquetRecordWriter.flushRowGroupToStore(InternalParquetRecordWriter.java:172)
> 	at org.apache.parquet.hadoop.InternalParquetRecordWriter.close(InternalParquetRecordWriter.java:114)
> 	at org.apache.parquet.hadoop.ParquetRecordWriter.close(ParquetRecordWriter.java:165)
> 	at org.apache.spark.sql.execution.datasources.parquet.ParquetOutputWriter.close(ParquetOutputWriter.scala:42)
> 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.releaseResources(FileFormatDataWriter.scala:57)
> 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.commit(FileFormatDataWriter.scala:74)
> 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:247)
> 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:242)
> 	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1394)
> 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:248)
> 	... 10 more
> 
> Driver stacktrace:
>   at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1891)
>   at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1879)
>   at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1878)
>   at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
>   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
>   at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1878)
>   at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:927)
>   at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:927)
>   at scala.Option.foreach(Option.scala:257)
>   at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:927)
>   at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2112)
>   at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2061)
>   at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2050)
>   at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
>   at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:738)
>   at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
>   at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:167)
>   ... 69 more
> Caused by: org.apache.spark.SparkException: Task failed while writing rows.
>   at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:257)
>   at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:170)
>   at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:169)
>   at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
>   at org.apache.spark.scheduler.Task.run(Task.scala:123)
>   at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
>   at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
>   at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
>   ... 3 more
> Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy
>   at org.apache.parquet.hadoop.codec.SnappyCompressor.compress(SnappyCompressor.java:67)
>   at org.apache.hadoop.io.compress.CompressorStream.compress(CompressorStream.java:81)
>   at org.apache.hadoop.io.compress.CompressorStream.finish(CompressorStream.java:92)
>   at org.apache.parquet.hadoop.CodecFactory$HeapBytesCompressor.compress(CodecFactory.java:165)
>   at org.apache.parquet.hadoop.ColumnChunkPageWriteStore$ColumnChunkPageWriter.writePage(ColumnChunkPageWriteStore.java:95)
>   at org.apache.parquet.

**Comment by vpanovk** [comment]
@Dreamter Thank you for reporting this!
Looks similar to https://github.com/big-data-europe/docker-spark/issues/62  (the solution would be to install libc6-compat, another thing to try is https://github.com/big-data-europe/docker-spark/commit/e96a216c06165a11231de76afa225fd0c54da01e )
Could you try these 2 fixes and let me know if they work? I'm very limited in terms of time lately, but I'd be happy to review your PR if you want it fixed sooner than I can deliver ;-)

**Comment by panovvv** [comment]
@Dreamter Thank you for reporting this!
Looks similar to big-data-europe/docker-spark#62 (the solution would be to install libc6-compat, another thing to try is big-data-europe/docker-spark@e96a216 )
Could you try these 2 fixes and let me know if they work? I'm very limited in terms of time lately, but I'd be happy to review your PR if you want it fixed sooner than I can deliver ;-)

**Comment by AbbyJoy** [comment]
Ran into the same error when trying to write to the hive metastore: `accountsDF.write.saveAsTable("mine.accounts_info")`
Might look into the fixes because I need this functionality to properly study for the CCA 175 cert.

**Comment by AbbyJoy** [comment]
Had to use both fixes you suggested, but both my error and the OP error are solved by the fix in this pull request: https://github.com/panovvv/hadoop-hive-spark-docker/pull/2

**Comment by panovvv** [comment]
merged it, should be fixed now. Thanks again Abby!

**Comment by vijaysarangapani** [comment]
Am facing below issue, could you some body help and am trying in docker container of my application and i tried /tmp 777 permissions and my jar is working as java -jar but it is not working in container and all possibilties 

 -Dorg.xerial.snappy.use.systemlib=true -Dorg.xerial.snappy.lib.path=/usr/lib/libsnappyjava.so

java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.pure. UnsafeUtil 
 at org.xerial.snappy.pure.SnappyRawCompressor.writeUncompressed Length (SnappyRawCompressor.java:405) 
 at org.xerial.snappy.pure.SnappyRawCompressor.compress (SnappyRawCompressor.java:111) 
 at org.xerial.snappy.pure. PureJavaSnappy.rawCompress (PureJavaSnappy.java:128) 
 at org.xerial.snappy.Snappy.rawCompress (Snappy.java:450) at org.xerial.snappy. Snappy.compress (Snappy.java:123) 
 at org.xerial.snappy. SnappyOutputStream.compress Input (SnappyOutputStream.java:380) 
 at org.xerial.snappy. SnappyOutputStream.flush(SnappyOutputStream.java:334) 
 at org.xerial. snappy. SnappyOutputStream.close(SnappyOutputStream.java:419) 
 at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:191) 
 at org.apache.kafka.common.record. MemoryRecordsBuilder.closeForRecordAppends (MemoryRecordsBuilder.java:314) 
 at org.apache.kafka.common.record.MemoryRecordsBuilder.close(MemoryRecordsBuilder.java:349) 
 at org.apache.kafka.clients.producer.internals. ProducerBatch.close(ProducerBatch.java:453) 
 at org.apache.kafka.clients.producer.internals. RecordAccumulator.drainBatchesForOneNode(RecordAccumulator.java:609) 
 at org.apache.kafka.clients.producer.internals. RecordAccumulator.drain (RecordAccumulator.java:636) 
 at org.apache.kafka.clients.producer.internals.Sender.sendProducerData (Sender.java:361) 
 at org.apache.kafka.clients.producer.internals.Sender.runOnce (Sender.java:327) 
 at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:243) 
 at java.base/java.lang.Thread.run(Thread.java:831) 
 Suppressed: org.xerial.snappy.SnappyError: [UNSUPPORTED PLATFORM] pure-java snappy requires access to java.nio.Buffer raw address field 
 at org.xerial.snappy.pure. UnsafeUtil.<clinit>(UnsafeUtil.java:49) 
 at org.xerial.snappy.pure.SnappyRawCompressor.writeUncompressed Length (SnappyRawCompressor.java:405) 
 at org.xerial.snappy.pure. SnappyRawCompressor.compress (SnappyRawCompressor.java:111) 
 at org.xerial.snappy.pure.PureJavaSnappy.rawCompress (PureJavaSnappy.java:128) 
 at org.xerial.snappy. Snappy.rawCompress (Snappy.java:450) at org.xerial.snappy. Snappy.compress (Snappy.java:123) 
 at org.xerial.snappy. SnappyOutputStream.compress Input (SnappyOutputStream.java:380) 
 at org.xerial.snappy. SnappyOutputStream.flush(SnappyOutputStream.java:334) 
 at java.base/java.io.DataOutputStream.flush(DataOutputStream.java:128) 
 at java.base/java.io.FilterOutputstream.close(FilterOutputStream.java:182)
